/* sensor.h */

#ifndef   	VPFE_SENSOR_COMMON_R_H_
#define   	VPFE_SENSOR_COMMON_R_H_

#define VPFE_SENSOR_CMD_INIT            0x00
#define VPFE_SENSOR_CMD_DEINIT          0x01

#define VPFE_SENSOR_CMD_SET_GAIN        0x10
#define VPFE_SENSOR_CMD_SET_EXP         0x11

#define VPFE_SENSOR_CMD_SET_MODE_LIVE   0x20
#define VPFE_SENSOR_CMD_SET_MODE_TRIG   0x21
#define VPFE_SENSOR_CMD_SET_SHP         0x22
#define VPFE_SENSOR_CMD_SET_SHD         0x23
#define VPFE_SENSOR_CMD_SET_BLACK_LEVEL 0x24
#define VPFE_SENSOR_CMD_ENABLE_FLASH    0x25
#define VPFE_SENSOR_CMD_SELECT_8BIT     0x26
#define VPFE_SENSOR_CMD_SELECT_10BIT    0x27
#define VPFE_SENSOR_CMD_SET_RED_GAIN    0x28
#define VPFE_SENSOR_CMD_SET_BLUE_GAIN   0x29
#define VPFE_SENSOR_CMD_ENABLE_GAMMA    0x3A
#define VPFE_SENSOR_CMD_RESET           0x3B
#define VPFE_SENSOR_CMD_SET_FLASH_DELAY 0x3C
#define VPFE_SENSOR_CMD_SET_SNAP_MODE   0x3D
#define VPFE_SENSOR_CMD_SET_SNAP_INTERVAL 0x3E
#define VPFE_SENSOR_CMD_ENABLE          0x3F

enum {
        SENSOR_SNAP_MODE_SINGLE = 1,
        SENSOR_SNAP_MODE_TWICE
};

#endif 	    /* !VPFE_SENSOR_COMMON_R_H_ */
